### ISSUE TITLE
NPE on plan route

### ISSUE THREAD

**Issue by patsonluk** [patsonluk/airline#209]
```
! @7e52601kg - Internal server error, for (POST) [/airlines/3864/plan-link] ->

play.api.UnexpectedException: Unexpected exception[NoSuchElementException: None.get]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:347)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:448)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:446)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:632)
        at scala.None$.get(Option.scala:631)
        at controllers.LinkApplication.$anonfun$planLink$1(LinkApplication.scala:501)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at play.api.mvc.Security$AuthenticatedBuilder.$anonfun$authenticate$1(Security.scala:199)
        at scala.Option.map(Option.scala:243)
        at play.api.mvc.Security$AuthenticatedBuilder.authenticate(Security.scala:198)
        at play.api.mvc.Security$AuthenticatedBuilder.invokeBlock(Security.scala:191)
        at play.api.mvc.Security$AuthenticatedBuilder.invokeBlock(Security.scala:181)
        at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:426)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:98)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:184)
        at scala.util.Try$.apply(Try.scala:212)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:184)

```

**Comment by patsonluk** [comment]
Probably multiple web tab or the airline reset took too long and the user started clicking plan link again - anyway, added check that airline's base overlaps with the from airport

**Comment by patsonluk** [comment]
Not a complete fix, but at least avoid NPE

https://github.com/patsonluk/airline/commit/14a5987b257077079b9756578694b8764e4d883d
