### ISSUE TITLE
NPE on addlink

### ISSUE THREAD

**Issue by patsonluk** [patsonluk/airline#210]
```
! @7e5imp48g - Internal server error, for (PUT) [/airlines/1581/links] ->

play.api.UnexpectedException: Unexpected exception[JsResultException: JsResultException(errors:List((,List(JsonValidationError(List(error.expected.jsnumber),ArraySeq())))))]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:347)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:448)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:446)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List(error.expected.jsnumber),ArraySeq())))))
        at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
        at play.api.libs.json.JsError.fold(JsResult.scala:64)
        at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
        at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
        at play.api.libs.json.JsDefined.as(JsLookup.scala:176)
        at controllers.package$LinkFormat$.reads(package.scala:128)
        at play.api.libs.json.JsValue.validate(JsValue.scala:17)
        at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
        at play.api.libs.json.JsObject.validate(JsValue.scala:124)
        at play.api.libs.json.JsReadable.as(JsReadable.scala:23)
        at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
        at play.api.libs.json.JsObject.as(JsValue.scala:124)
        at controllers.LinkApplication.addLinkBlock(LinkApplication.scala:218)
        at controllers.LinkApplication.$anonfun$addLink$1(LinkApplication.scala:360)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at play.api.mvc.Security$AuthenticatedBuilder.$anonfun$authenticate$1(Security.scala:199)
        at scala.Option.map(Option.scala:243)
        at play.api.mvc.Security$AuthenticatedBuilder.authenticate(Security.scala:198)
        at play.api.mvc.Security$AuthenticatedBuilder.invokeBlock(Security.scala:191)
        at play.api.mvc.Security$AuthenticatedBuilder.invokeBlock(Security.scala:181)
        at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:426)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:98)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:184)
        at scala.util.Try$.apply(Try.scala:212)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:184)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:223)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:442)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
        ... 11 common frames omitted
```

**Comment by patsonluk** [comment]
bad format price input
