### ISSUE TITLE
departure board exception

### ISSUE THREAD

**Issue by patsonluk** [patsonluk/airline#276]
Caused by: java.lang.ArithmeticException: / by zero
        at controllers.Application.$anonfun$getTimeSlotStatus$1(Application.scal                                                                                                       a:327)
        at controllers.Application.$anonfun$getTimeSlotStatus$1$adapted(Applicat                                                                                                       ion.scala:314)
        at scala.Option.map(Option.scala:243)
        at controllers.Application.getTimeSlotStatus(Application.scala:314)
        at controllers.Application.$anonfun$getDepartures$9(Application.scala:29                                                                                                       2)
        at scala.collection.immutable.List.map(List.scala:226)

**Comment by patsonluk** [comment]
This is caused by consumption history which has zero frequency, which is fixed in ca95c9c604bec1a293550b9b7143132ff0c2dc53
